- .gitignore
- src/main/java/com/moing/backend/domain/auth/presentation/AuthController.java
- src/main/java/com/moing/backend/domain/auth/presentation/AuthRedirectController.java
- src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepositoryImpl.java
> feat: add AuthRedirectController

- src/main/java/com/moing/backend/domain/board/application/service/AlarmBoardUserCase.java
- src/main/java/com/moing/backend/domain/board/application/service/CreateBoardUserCase.java
- src/main/java/com/moing/backend/domain/board/application/service/DeleteBoardUserCase.java
- src/main/java/com/moing/backend/domain/board/application/service/GetBoardUserCase.java
- src/main/java/com/moing/backend/domain/board/application/service/SendBoardAlarmUserCase.java
- src/main/java/com/moing/backend/domain/board/application/service/UpdateBoardUserCase.java
- src/main/java/com/moing/backend/domain/boardComment/application/service/CreateBoardCommentUserCase.java
- src/main/java/com/moing/backend/domain/boardComment/application/service/DeleteBoardCommentUserCase.java
- src/main/java/com/moing/backend/domain/boardComment/application/service/GetBoardCommentUserCase.java
- src/main/java/com/moing/backend/domain/team/application/service/SendTeamAlarmUserCase.java
- src/main/java/com/moing/backend/domain/team/presentation/AdminTeamController.java
- src/main/java/com/moing/backend/domain/team/presentation/constant/TeamResponseMessage.java
- src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepository.java
- src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/teamMember/domain/service/TeamMemberGetService.java
- src/main/java/com/moing/backend/global/config/fcm/FcmConfig.java
- src/main/java/com/moing/backend/global/config/fcm/constant/NewUploadTitle.java
- src/main/java/com/moing/backend/global/config/fcm/dto/request/MultiRequest.java
- src/main/java/com/moing/backend/global/config/fcm/dto/request/SingleRequest.java
- src/main/java/com/moing/backend/global/config/fcm/dto/response/MultiResponse.java
- src/main/java/com/moing/backend/global/config/fcm/dto/response/SingleResponse.java
- src/main/java/com/moing/backend/global/config/fcm/exception/FirebaseException.java
- src/main/java/com/moing/backend/global/config/fcm/exception/InitializeException.java
- src/main/java/com/moing/backend/global/config/fcm/exception/MessagingException.java
- src/main/java/com/moing/backend/global/config/fcm/exception/NotificationException.java
- src/main/java/com/moing/backend/global/config/fcm/service/FcmService.java
- src/main/java/com/moing/backend/global/response/ErrorCode.java
- 알림설정 환경 설정 
- 공지 신규 알림
- 소모임 승인, 반려 알림
알림설정 환경 설정 
https://github.com/Modagbul/MOING_server_release/blob/c830a0440a873b49728b9365e396ea8ee9b36051/src/main/java/com/moing/backend/global/config/fcm/service/FcmService.java#L17-L149
@yeopseung 이렇게 하는게 맞는지 확인 부탁드립니다...!
공지 신규 알림
https://github.com/Modagbul/MOING_server_release/blob/c830a0440a873b49728b9365e396ea8ee9b36051/src/main/java/com/moing/backend/domain/board/application/service/SendBoardAlarmUserCase.java#L19-L41
소모임 승인, 반려 알림 보내는 것은 관리자 페이지에서 하지 않고, 이 서버(FO)에서 API를 만들어 관리자 서버에서 (BO)에서 FO에 알림을 요청하는 프로세스로 했습니다. 
이유: 소모임 승인, 반려도 관리자 페이지에서 하기에는 fcm환경설정을 또 해야하는 불편함이 있었고 소모임을 승인하는 절차가 아닌 알림을 보내는 것은 보안상으로도 크게 문제되지 않을 것 이라고 생각했기 때문입니다!
https://github.com/Modagbul/MOING_server_release/blob/c830a0440a873b49728b9365e396ea8ee9b36051/src/main/jav …
> Feat/alarm : 알람 기능 

- src/docs/asciidoc/Auth-API.adoc
- src/main/java/com/moing/backend/domain/auth/application/dto/request/SignUpRequest.java
- src/main/java/com/moing/backend/domain/auth/application/dto/response/GoogleUserResponse.java
- src/main/java/com/moing/backend/domain/auth/application/dto/response/KakaoAccessTokenResponse.java
- src/main/java/com/moing/backend/domain/auth/application/dto/response/KakaoUserResponse.java
- src/main/java/com/moing/backend/domain/auth/application/service/SignUpUserCase.java
- src/main/java/com/moing/backend/domain/auth/application/service/kakao/KakaoTokenUserCase.java
- src/main/java/com/moing/backend/domain/member/application/mapper/MemberMapper.java
- src/main/java/com/moing/backend/domain/member/domain/constant/Gender.java
- src/main/java/com/moing/backend/domain/member/domain/entity/Member.java
- src/main/java/com/moing/backend/global/util/AesConverter.java
- src/main/java/com/moing/backend/global/util/StartupRunner.java
- src/test/java/com/moing/backend/domain/auth/presentation/AuthControllerTest.java
> hotFix/auth : 로그인, 회원가입 수정

- src/main/java/com/moing/backend/global/config/fcm/FcmConfig.java
> hotfix: fcmConfig 수정

- src/docs/asciidoc/Mission-API.adoc
- src/docs/asciidoc/MissionGatherBoard-API.adoc
- src/main/java/com/moing/backend/domain/mission/application/service/MissionReadUseCase.java
- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionRepository.java
- src/main/java/com/moing/backend/domain/mission/presentation/MissionController.java
- src/main/java/com/moing/backend/domain/mission/presentation/constant/MissionResponseMessage.java
- src/test/java/com/moing/backend/domain/mission/representation/MissionControllerTest.java
미션 추천을 위한 팀 카테고리 리턴 Api 입니다! 
https://github.com/Modagbul/MOING_Server_Release/blob/c3763e2040dee16327249da6af2408ca47e4cbcc/src/main/java/com/moing/backend/domain/mission/presentation/MissionController.java#L83-L89
https://github.com/Modagbul/MOING_Server_Release/blob/c3763e2040dee16327249da6af2408ca47e4cbcc/src/test/java/com/moing/backend/domain/mission/representation/MissionControllerTest.java#L307-L345
> feat : 미션 추천을 위한 팀 카테고리 리턴, Docs 수정

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
- 종료된 미션 status Null 들어가는 오류 수정
> feat : 종료된 미션 status Null 들어가는 오류 수정'

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
- 반복미션 조회 mission.way.toStringvalue()
> fix : 반복미션 조회 mission.way.toStringvalue()

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : 반복 미션 조회 수정

- src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveUpdateUseCase.java
- src/main/java/com/moing/backend/domain/missionArchive/exception/NoAccessMissionArchiveException.java
> fix : NoAccessMissionArchiveException.java 위치 에러

- firebase-key.json
- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
- src/main/java/com/moing/backend/domain/missionState/domain/repository/MissionStateCustomRepository.java
- src/main/java/com/moing/backend/domain/missionState/domain/repository/MissionStateCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/missionState/domain/service/MissionStateQueryService.java
- src/main/java/com/moing/backend/domain/missionState/exception/MissionStateException.java
- src/main/java/com/moing/backend/domain/missionState/exception/NotFoundMissionStateException.java
> feat : 미션 인증 마감 스케쥴러 구현중

- src/main/java/com/moing/backend/domain/mission/application/dto/res/GatherRepeatMissionRes.java
- src/main/java/com/moing/backend/domain/mission/application/dto/res/GatherSingleMissionRes.java
- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- src/test/java/com/moing/backend/domain/missionArchive/representation/MissionGatherControllerTest.java
> fix : 미션 모아보기-teamId 추가

- src/docs/asciidoc/api.adoc
> feat : 모잉불 조회 api 문서 반영

- src/main/java/com/moing/backend/domain/mission/application/service/MissionCreateUseCase.java
- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
> fix : 미션 생성 개수 제한 버그  수정

- src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveDeleteUseCase.java
- src/main/java/com/moing/backend/domain/missionArchive/presentation/MissionArchiveController.java
- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateUseCase.java
- src/main/java/com/moing/backend/domain/missionState/domain/repository/MissionStateCustomRepository.java
- src/main/java/com/moing/backend/domain/missionState/domain/repository/MissionStateCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/missionState/domain/service/MissionStateDeleteService.java
- src/main/java/com/moing/backend/domain/missionState/domain/service/MissionStateQueryService.java
- src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java
- 미션 재인증하기, 다시 미션 인증하기 로직 변경에 따른 미션 인증 삭제하기 로직 추가
> feat : 미션 인증 삭제하기 로직 추가

- src/docs/asciidoc/MissionArchive-API.adoc
> chore : 미션 인증 삭제 Api docs 반영

- src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/team/domain/service/TeamGetService.java
- src/main/java/com/moing/backend/global/util/StartupRunner.java
소모임 조회할 때 삭제된 것도 조회 오류 해결
소모임 조회할 때 삭제된 것도 조회 오류 해결
> fix: 소모임 조회할 때 삭제된 것도 조회 오류 해결

- src/main/java/com/moing/backend/domain/auth/application/service/google/GoogleSignInUserCase.java
- src/main/java/com/moing/backend/domain/auth/application/service/google/GoogleTokenUserCase.java
> fix: 구글 로그인 토큰 검증 오류 해결

- src/main/java/com/moing/backend/domain/member/domain/entity/Member.java
- src/main/java/com/moing/backend/domain/mypage/application/service/ProfileUserCase.java
- src/main/java/com/moing/backend/domain/mypage/application/service/WithdrawUserCase.java
- src/main/java/com/moing/backend/domain/team/application/service/UpdateTeamUserCase.java
- src/main/java/com/moing/backend/global/config/s3/S3Service.java
- 이미지 삭제 메서드 추가
- 회원탈퇴 메서드 변경해서 오류 해결
> s3 이미지 삭제 메서드 추가 및 회원탈퇴 오류 해결

- .gitignore
- src/main/java/com/moing/backend/domain/auth/application/service/apple/AppleWithdrawUserCase.java
- src/main/java/com/moing/backend/global/config/sns/AppleConfig.java
> refactor: 애플 키 가져오는 함수 confiuration으로 관리

- build.gradle
- src/main/java/com/moing/backend/domain/member/domain/entity/Member.java
- src/main/java/com/moing/backend/domain/team/application/service/CreateTeamUserCase.java
- src/main/java/com/moing/backend/global/exception/GlobalExceptionHandler.java
- src/main/java/com/moing/backend/global/util/SlackService.java
서버 500 에러 발생 시 ,소모임 생성 시 
slack Alarm 비동기적으로 보내는 기능 추가
> slack Alarm 기능 추가 

- src/main/java/com/moing/backend/global/util/SlackService.java
- src/test/java/com/moing/backend/config/CommonControllerTest.java
> fix: test시 빈을 찾을 수 없는 문제 해결

- src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/team/presentation/constant/TeamResponseMessage.java
- 승인 되었을때만 현재 시간으로 approvalTime설정하게 수정
- 소모임 조회 시 승인 여부 추가 수정
> 소모임 조회 수정 

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
> fix : 한번미션 wait 리턴

- src/main/java/com/moing/backend/domain/mypage/presentation/MyPageController.java
- src/main/java/com/moing/backend/domain/mypage/presentation/constant/MypageResponseMessage.java
> feat: 회원가입 여부 확인 추가

- src/main/java/com/moing/backend/domain/team/application/service/CreateTeamUseCase.java
> fix: 임시로 생성하면 승인되게 수정

- src/main/java/com/moing/backend/domain/boardComment/application/dto/response/CommentBlocks.java
> fix: 게시글 댓글 삭제 여부 수정

- src/main/java/com/moing/backend/domain/mission/application/dto/res/SingleMissionBoardRes.java
- src/main/java/com/moing/backend/domain/team/application/service/ApproveTeamUseCase.java
> fix: fcmService 의존하게 수정

- src/docs/asciidoc/Team-API.adoc
- src/main/java/com/moing/backend/domain/team/application/dto/response/GetTeamCountResponse.java
- src/main/java/com/moing/backend/domain/team/application/dto/response/TeamBlock.java
- src/main/java/com/moing/backend/domain/team/application/service/GetTeamUseCase.java
- src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepository.java
- src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/team/domain/service/TeamGetService.java
- src/main/java/com/moing/backend/domain/team/presentation/TeamController.java
- src/main/java/com/moing/backend/domain/team/presentation/constant/TeamResponseMessage.java
- src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java
> feat: 소모임 개수와 이름 조회 기능 추가

- src/main/java/com/moing/backend/domain/board/application/service/SendBoardAlarmUseCase.java
- src/main/java/com/moing/backend/global/config/fcm/constant/NewNoticeUploadMessage.java
- src/main/java/com/moing/backend/global/config/fcm/service/FcmService.java
> fix: 공지 알림 문구 수정

- src/main/java/com/moing/backend/domain/mypage/application/service/ProfileUseCase.java
- src/main/java/com/moing/backend/global/config/s3/S3Service.java
- 마이페이지 오류 수정
- s3에서 삭제하기 전 존재하는지 확인
- s3 삭제 비동기로 수정
> hotfix: 마이페이지 오류 수정

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
> fix : 모임아 제발 사라지지마

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : 소모임 메인 미션 인증물 사진 조회

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : 소모임 메인페이지 인증 사진 조회 로직 수정

- src/main/java/com/moing/backend/domain/mypage/application/service/ProfileUseCase.java
> hotfix: 프로필 사진 수정 null 체크

- src/main/java/com/moing/backend/domain/team/application/dto/response/GetTeamCountResponse.java
- src/main/java/com/moing/backend/domain/team/application/service/GetTeamUseCase.java
- src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java
> feat: 소모임 개수 보낼 때 유저 닉네임 추가

- src/main/java/com/moing/backend/domain/missionArchive/domain/entity/MissionArchive.java
> fix : 인증물 글자수 제한 1000자 -> 4000byte

- src/main/java/com/moing/backend/domain/missionArchive/presentation/MissionArchiveController.java
> chore : 불필요한 method import 삭제

- src/main/java/com/moing/backend/domain/auth/application/service/ReissueTokenUseCase.java
- src/main/java/com/moing/backend/domain/mypage/application/service/ProfileUseCase.java
- src/main/java/com/moing/backend/domain/team/application/dto/request/UpdateTeamRequest.java
- src/main/java/com/moing/backend/domain/team/application/service/CheckLeaderUseCase.java
- src/main/java/com/moing/backend/domain/team/application/service/DisbandTeamUseCase.java
- src/main/java/com/moing/backend/domain/team/application/service/UpdateTeamUseCase.java
- src/main/java/com/moing/backend/global/config/s3/S3Service.java
- src/main/java/com/moing/backend/global/config/security/jwt/NotFoundRefreshToken.java
- src/main/java/com/moing/backend/global/config/security/jwt/TokenUtil.java
- src/main/java/com/moing/backend/global/utils/AesUtil.java
- src/main/java/com/moing/backend/global/utils/StartupRunner.java
- src/main/java/com/moing/backend/global/utils/UpdateUtils.java
- 소모임장 권한 함수 추가 및 수정
- 소모임 모든 필드 입력 안해도 수정되게 
- 이미지 삭제
- 소모임장 권한 함수 추가 
https://github.com/Modagbul/MOING_Server_Release/blob/589ceb505f065cc336834b0f3eb2acefb3efbf55/src/main/java/com/moing/backend/domain/team/application/service/CheckLeaderUseCase.java#L12-L24
- 소모임 모든 필드 입력 안해도 수정되게 수정
https://github.com/Modagbul/MOING_Server_Release/blob/589ceb505f065cc336834b0f3eb2acefb3efbf55/src/main/java/com/moing/backend/domain/team/application/service/UpdateTeamUseCase.java#L24-L41
- 이미지 삭제
https://github.com/Modagbul/MOING_Server_Release/blob/589ceb505f065cc336834b0f3eb2acefb3efbf55/src/main/java/com/moing/backend/global/utils/UpdateUtils.java#L21-L26
이거 호출해서 사용하면 됩니다
> 소모임장 권한 함수 / 이미지 삭제 함수 

- src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/MissionArchiveRes.java
> fix : 불필요한 필드 삭제

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
> fix : having 절 주석처리 취소

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/mission/domain/service/MissionQueryService.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : 인증완료한 반복미션 보드

- src/main/java/com/moing/backend/domain/board/application/dto/response/BoardBlocks.java
- src/main/java/com/moing/backend/domain/board/application/mapper/BoardMapper.java
- src/main/java/com/moing/backend/domain/board/domain/repository/BoardCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/boardComment/application/dto/response/CommentBlocks.java
- src/main/java/com/moing/backend/domain/boardComment/domain/repository/BoardCommentCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/history/application/service/SaveSingleAlarmHistoryUseCase.java
- src/main/java/com/moing/backend/domain/mypage/application/dto/response/GetMyPageTeamBlock.java
- src/main/java/com/moing/backend/domain/team/application/dto/response/TeamBlock.java
- src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepositoryImpl.java
- src/main/java/com/moing/backend/global/config/fcm/service/FcmService.java
- src/test/java/com/moing/backend/domain/boardComment/presentation/BoardCommentControllerTest.java
- src/test/java/com/moing/backend/domain/mypage/presentation/MypageControllerTest.java
- src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java
- 소모임 조회할 때 프로필 이미지 추가
- 댓글 조회할 때 작성 날짜 추가
- 홈 화면 / 마이페이지 조회할 때 소모임 프로필 이미지 추가
> 소모임 조회할 때 프로필 이미지 추가

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : 엄청난 오류 일단 수정

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : mission board 에서 wait 상태 추가

- src/main/java/com/moing/backend/domain/board/application/service/SendBoardAlarmUseCase.java
- src/main/java/com/moing/backend/domain/fire/application/service/FireThrowAlarmUseCase.java
- src/main/java/com/moing/backend/domain/member/domain/entity/Member.java
- src/main/java/com/moing/backend/domain/member/domain/service/MemberSaveService.java
- src/main/java/com/moing/backend/domain/mission/application/service/SendMissionCreateAlarmUseCase.java
- src/main/java/com/moing/backend/domain/mypage/application/service/SignOutUseCase.java
- src/main/java/com/moing/backend/domain/team/application/service/ApproveTeamUseCase.java
- src/main/java/com/moing/backend/domain/team/application/service/RejectTeamUseCase.java
- src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepository.java
- src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/teamMember/domain/service/TeamMemberGetService.java
- src/main/java/com/moing/backend/global/config/fcm/dto/event/MultiFcmEvent.java
- src/main/java/com/moing/backend/global/config/fcm/dto/event/SingleFcmEvent.java
- src/main/java/com/moing/backend/global/config/fcm/service/FcmService.java
- src/main/java/com/moing/backend/global/config/fcm/util/FcmMessageUtil.java
- src/main/java/com/moing/backend/global/utils/StartupRunner.java
로그아웃, 알림 off 한 경우에 push 알림은 안보내고 알림 히스토리에는 저장되게 수정
- 로그아웃 - > 푸시알림을 보냈는데 푸시 알림을 안보내게 수정 
- 알림 off -> 알림 히스토리에도 저장을 안했는데 저장되게 수정
> 로그아웃, 알림 Off한 경우에 push 알림은 안보내고 알림 히스토리에는 저장되게 수정

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : missionArchive -> missionState 변경 중에 생긴 오류 해결 

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : dateInRangeByState 수정

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/mission/domain/service/MissionQueryService.java
> fix : 미션 진행중에 한번미션 안뜨는 오류 수정

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
> fix : 진행중 미션에 완료한 미션 뜨지 않도록

- src/main/java/com/moing/backend/domain/mission/presentation/MissionController.java
> fix : Missioncontroller 수정

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
> fix : 반복미션 생성 개수제한 로직 수정

- src/main/java/com/moing/backend/domain/missionArchive/domain/entity/MissionArchive.java
> fix : missionArchive 와 missionHeart Cascade 관계 재정리

- src/main/java/com/moing/backend/domain/mission/application/service/MissionRemindAlarmUseCase.java
- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepository.java
- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/mission/domain/service/MissionQueryService.java
- src/main/java/com/moing/backend/domain/mission/presentation/MissionController.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveScheduleQueryService.java
- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
- src/main/java/com/moing/backend/domain/teamScore/application/service/TeamScoreLogicUseCase.java
- src/main/java/com/moing/backend/global/config/fcm/constant/RemindMissionTitle.java
- src/main/java/com/moing/backend/global/config/fcm/util/FcmMessageUtil.java
> feat : 미션 리마인드 알림 작동

- src/main/java/com/moing/backend/domain/report/application/mapper/ReportMapper.java
- src/main/java/com/moing/backend/domain/report/application/service/ReportCreateUseCase.java
- src/main/java/com/moing/backend/domain/report/domain/entity/Report.java
> feat : 신고하기 (게시물/미션인증)  내용 변경 로직 추가

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : 신고당한 인증 사진 소모임 메인에 보이지 않게

- src/main/java/com/moing/backend/domain/mission/application/service/MissionRemindAlarmUseCase.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepository.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveRepository.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveScheduleQueryService.java
> fix : 오전 8시 미션 리마인드 알림 로직 고도화

- src/main/java/com/moing/backend/domain/auth/application/dto/request/SignUpRequest.java
- src/main/java/com/moing/backend/domain/member/domain/entity/Member.java
- 회원가입할 때 성별과 생일에서 건너뛰기 기능을 추가해 이에 따른 널 체크 제외
> fix: 회원가입할 때 닉네임만 필수로 받게 수정

- src/main/java/com/moing/backend/domain/mission/application/dto/res/GatherRepeatMissionRes.java
- src/main/java/com/moing/backend/domain/mission/application/dto/res/GatherSingleMissionRes.java
- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- src/test/java/com/moing/backend/domain/missionArchive/representation/MissionGatherControllerTest.java
> fix : 진행중 미션 리턴값 추가

- src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveDeleteUseCase.java
- src/main/java/com/moing/backend/global/utils/UpdateUtils.java
> fix : 다시 인증하기 로직에 s3 삭제 로직 추가

- src/main/java/com/moing/backend/domain/board/application/dto/response/BoardBlocks.java
- src/main/java/com/moing/backend/domain/board/application/mapper/BoardMapper.java
- src/main/java/com/moing/backend/domain/board/application/service/CreateBoardUseCase.java
- src/main/java/com/moing/backend/domain/board/domain/entity/Board.java
- src/main/java/com/moing/backend/domain/board/domain/repository/BoardCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/boardComment/application/mapper/BoardCommentMapper.java
- src/main/java/com/moing/backend/domain/boardComment/application/service/CreateBoardCommentUseCase.java
- src/main/java/com/moing/backend/domain/boardComment/domain/entity/BoardComment.java
- src/main/java/com/moing/backend/domain/boardComment/domain/repository/BoardCommentCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/mypage/domain/entity/Feedback.java
- src/test/java/com/moing/backend/domain/board/presentation/BoardControllerTest.java
- 게시글 , 댓글 조회할 때 닉네임, 프로필 이미지 바뀐 것 반영하게 수정
> fix: 게시글 조회할 때 닉네임, 프로필 이미지 바뀐 것 반영하게 수정

- src/main/java/com/moing/backend/domain/missionArchive/application/mapper/MissionArchiveMapper.java
> fix :모임원 인증물 좋아요 mapper 변경

- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : 종료된 미션 정렬기준 변경

- src/docs/asciidoc/MissionArchive-API.adoc
- src/main/java/com/moing/backend/BackendApplication.java
- src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/MyArchiveStatus.java
- src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveReadUseCase.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepository.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveQueryService.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveScheduleQueryService.java
- src/main/java/com/moing/backend/domain/missionArchive/presentation/MissionArchiveController.java
- src/test/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImplTest.java
- src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java
> feat : 미션 인증 상태 조회 api 추가

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
> fix : 리마인드 알림 team.isDeleted.ne(true)

- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
> fix : 미션 리마인드 알림 스케쥴러 주기 원상복구

- src/docs/asciidoc/Block-API.adoc
- src/main/java/com/moing/backend/domain/block/application/mapper/BlockMapper.java
- src/main/java/com/moing/backend/domain/block/application/service/BlockCreateUseCase.java
- src/main/java/com/moing/backend/domain/block/application/service/BlockDeleteUseCase.java
- src/main/java/com/moing/backend/domain/block/application/service/BlockReadUseCase.java
- src/main/java/com/moing/backend/domain/block/domain/entity/Block.java
- src/main/java/com/moing/backend/domain/block/domain/repository/BlockCustomRepository.java
- src/main/java/com/moing/backend/domain/block/domain/repository/BlockCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/block/domain/repository/BlockRepository.java
- src/main/java/com/moing/backend/domain/block/domain/service/BlockDeleteService.java
- src/main/java/com/moing/backend/domain/block/domain/service/BlockQueryService.java
- src/main/java/com/moing/backend/domain/block/domain/service/BlockSaveService.java
- src/main/java/com/moing/backend/domain/block/exception/BlockException.java
- src/main/java/com/moing/backend/domain/block/exception/NotFoundBlockException.java
- src/main/java/com/moing/backend/domain/block/presentation/BlockController.java
- src/main/java/com/moing/backend/domain/block/presentation/constant/BlockResponseMessage.java
- src/main/java/com/moing/backend/domain/board/application/dto/response/GetBoardDetailResponse.java
- src/main/java/com/moing/backend/domain/board/application/mapper/BoardMapper.java
- src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/PersonalArchiveRes.java
- src/main/java/com/moing/backend/domain/missionArchive/application/mapper/MissionArchiveMapper.java
- src/main/java/com/moing/backend/domain/report/application/dto/BlockMemberRes.java
- src/main/java/com/moing/backend/global/response/ErrorCode.java
- src/test/java/com/moing/backend/domain/block/presentation/BlockControllerTest.java
- src/test/java/com/moing/backend/domain/board/presentation/BoardControllerTest.java
- src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java
> feat/block : 차단하기 api 

- src/docs/asciidoc/api.adoc
> feat : API 문서 반영

- src/main/java/com/moing/backend/domain/boardComment/domain/entity/BoardComment.java
- src/main/java/com/moing/backend/domain/report/application/service/ReportCreateUseCase.java
- src/main/java/com/moing/backend/domain/report/domain/entity/constant/ReportType.java
- src/test/java/com/moing/backend/domain/board/presentation/BoardControllerTest.java
- src/test/java/com/moing/backend/domain/report/presentation/ReportControllerTest.java
> feat : 댓글 신고하기 기능 추가

- src/main/java/com/moing/backend/domain/board/application/dto/response/BoardBlocks.java
- src/main/java/com/moing/backend/domain/board/domain/repository/BoardCustomRepositoryImpl.java
- src/test/java/com/moing/backend/domain/board/presentation/BoardControllerTest.java
> feat: 게시글 전체 조회에서 작성자 id 추가

- src/main/java/com/moing/backend/domain/report/application/dto/BlockMemberRes.java
> fix : BlockMemerRes Constructor 추가

- src/main/java/com/moing/backend/domain/board/domain/repository/BoardCustomRepositoryImpl.java
> fix : 게시물 전체조회 null 값

- src/main/java/com/moing/backend/domain/board/application/dto/response/BoardBlocks.java
> fix : 탈퇴한 멤버 makerId

- src/main/java/com/moing/backend/domain/board/application/mapper/BoardMapper.java
> fix : 게시물 상세 조회 탈퇴한 인원 관리

- src/main/java/com/moing/backend/domain/board/domain/repository/BoardCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/boardRead/domain/entity/BoardRead.java
- src/main/java/com/moing/backend/domain/boardRead/domain/repository/BoardReadRepository.java
- src/main/java/com/moing/backend/domain/boardRead/domain/service/BoardReadSaveService.java
> fix: 안 읽은 게시글 음수 방지

- src/main/java/com/moing/backend/domain/mission/application/service/MissionUpdateUseCase.java
- src/main/java/com/moing/backend/domain/mission/domain/entity/Mission.java
> fix : 반복미션 종료 로직에 종료 시간 추가

- .deploy/Dockerfile
- .deploy/deploy_dev.sh
- .deploy/deploy_prod.sh
- .github/workflows/CD-dev.yml
- .github/workflows/CD-prod.yml
- .github/workflows/CI-dev.yml
- .github/workflows/CI-prod.yml
- deploy: 배포 프로세스 pord, dev 나누기
- 개발 서버 ,운영 서버 나누기 
- main 브랜치 -> 개발 서버 / release 브랜치 -> 운영 서버
> deploy: 배포 프로세스 prod, dev 나누기

- src/main/java/com/moing/backend/domain/team/application/service/SignInTeamUseCase.java
- src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepository.java
- src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/team/domain/service/TeamGetService.java
> fix: 존재하지 않은 팀에 대한 에러 처리

- src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveCreateUseCase.java
- src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveReadUseCase.java
- src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveUpdateUseCase.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepository.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveQueryService.java
- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateUseCase.java
- src/main/java/com/moing/backend/domain/missionState/domain/repository/MissionStateCustomRepositoryImpl.java
- 반복미션 점수 로직 버그 수정
- 미션 인증 관련 불필요한 로직 삭제 
- 미션 인증 관련 로직 단순화
- 불필요한 메소드 삭제
> fix : 반복미션 점수 업데이트 버그 수정 및 불필요한 메소드 삭제

- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateUseCase.java
> fix : 한번미션 점수 반영 안되는 버그

- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
> fix : 개발서버에서 스케쥴링 동작 위한 주석 처리

- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
- src/main/java/com/moing/backend/domain/teamScore/application/service/TeamScoreLogicUseCase.java
> fix : 한번 미션 마감 로직 위한 로그 추가

- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
- src/main/java/com/moing/backend/domain/teamScore/application/service/TeamScoreLogicUseCase.java
> fix : 개발 서버 스케쥴링 off

- src/main/java/com/moing/backend/domain/board/application/dto/request/CreateBoardRequest.java
- src/main/java/com/moing/backend/domain/boardComment/application/dto/request/CreateBoardCommentRequest.java
- src/main/java/com/moing/backend/domain/boardComment/application/dto/response/CommentBlocks.java
> fix: 탈퇴한 유저 게시글 댓글 오류 수정

- src/main/java/com/moing/backend/domain/fire/domain/repository/FireCustomRepositoryImpl.java
> fix : 지난주차 미션 완료자 불던지기 안보이는 버그#204

- src/main/java/com/moing/backend/domain/board/application/dto/request/CreateBoardRequest.java
- src/main/java/com/moing/backend/domain/board/domain/entity/Board.java
> fix: 공지/게시글 글자수 제한 수정

- src/main/java/com/moing/backend/domain/alarm/application/SingleAlarmEventUseCase.java
- src/main/java/com/moing/backend/domain/boardComment/application/service/SendCommentAlarmUseCase.java
- src/main/java/com/moing/backend/domain/fire/application/service/FireThrowAlarmUseCase.java
- src/main/java/com/moing/backend/global/config/fcm/dto/event/SingleFcmEvent.java
- 댓글 알림 안오는 오류 수정 
- 댓글 알림 안오는 오류 수정
- 내가 작성한 게시글의 댓글에는 알림 안오게 수정
> MNG-06 fix: 댓글 알림 안오는 오류 수정

- src/main/java/com/moing/backend/domain/mission/application/mapper/MissionMapper.java
- src/main/java/com/moing/backend/domain/mission/application/service/MissionCreateUseCase.java
- src/main/java/com/moing/backend/domain/mission/application/service/MissionDeleteUseCase.java
- src/main/java/com/moing/backend/domain/mission/application/service/MissionUpdateUseCase.java
- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- 소모임장이 생성한 미션이 아니더라도, 소모임장에게 수정/삭제 권한 부여
- MissionMapper에 member 파라미터 추가 ..
> MNG-12 fix : 소모임장에게 모든 미션 권한 부여 (isLeader 값)

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- 소모임장 수정 삭제 권한 부여 관련 customImpl 에러 해결
- BooleanExpression isLeader = (mission.makerId.eq(memberId)).or(mission.team.leaderId.eq(memberId)); 은 안된다네요 ㅜㅜ
> MNG-12 fix : 소모임장 수정 삭제 권한 부여 관련 customImpl 에러 해결

- src/main/java/com/moing/backend/domain/boardComment/application/service/SendCommentAlarmUseCase.java
- src/main/java/com/moing/backend/domain/boardComment/domain/repository/BoardCommentCustomRepository.java
- src/main/java/com/moing/backend/domain/boardComment/domain/repository/BoardCommentCustomRepositoryImpl.java
- src/main/java/com/moing/backend/domain/boardComment/domain/service/BoardCommentGetService.java
[MNG-17](https://github.com/Modagbul/MOING_Server_Release/pull/240)
> [release] MNG-17

- src/test/java/com/moing/backend/domain/board/domain/BoardRepositoryTest.java
> MNG-17 delete: 레포지토리 테스트 코드 주석 처리

- src/main/java/com/moing/backend/domain/mission/application/service/MissionUpdateUseCase.java
미션 수정 시, 소모임장/생성자 권한 로직에 오류가 있었습니다
예외처리 관련 조건 수정해 반영하였습니다.
> MNG-12 fix : 미션 수정 소모임장/생성자 권한 로직 버그

- src/main/java/com/moing/backend/domain/team/domain/entity/Team.java
- src/main/java/com/moing/backend/domain/teamScore/domain/entity/TeamScore.java
목표보드 레벨과 미션보드 레벨이 다른 버그 수정
Team 엔티티의 불꽃 레벨 업데이트 메소드를 수정하였습니다!
> MNG-18 fix : 목표보드 레벨과 미션보드 레벨이 다른 버그 수정

- src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveDeleteUseCase.java
- src/main/java/com/moing/backend/domain/team/domain/entity/Team.java
- src/main/java/com/moing/backend/domain/teamScore/domain/entity/TeamScore.java
[MNG-18
](https://github.com/Modagbul/MOING_Server_Release/pull/254)
> [release] MNG-18

- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
미션 리마인드 시간 변경에 따른 변경입니다.
- 미션 리마인드 알림 시각 오전 8시 → 오후 8시
- 일요일/월요일 오후 8시에 운영되던 반복미션 리마인드 알림 삭제
> MNG-19 fix : 미션 리마인드 시간 변경 및 일/월 리마인드 알림 삭제

- src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateScheduleUseCase.java
오후 5시에 예정된 업데이트 독려 푸시알림 스케쥴링을 주석처리합니다!
> hotfix fix : 업데이트 독려 푸시알림 스케쥴링 삭제

- src/main/java/com/moing/backend/global/config/security/SecurityConfig.java
- 로그 모니터링을 위한 security 허용범위 수정
> deploy: 로그 모니터링을 위한 security 허용범위 수정

- src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java
> MNG-21 : 미션 인증 문구 추가 API 문서 반영

- src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
- 한번 미션 repositoryImpl 에서 리턴 타입 변경 부분 반영되지 않은것이 있어 수정하여 머지합니다!
> fix : 반복미션 모아보기 인증 인원수 리턴 타입 변경

- src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/PersonalArchiveRes.java
- src/main/java/com/moing/backend/domain/missionArchive/application/mapper/MissionArchiveMapper.java
- src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java
> MNG-20 feat: 모두의 인증 현황에 미션 인증 댓글 수 추가

- src/main/java/com/moing/backend/domain/member/dto/response/UserProperty.java
- src/main/java/com/moing/backend/domain/team/application/dto/response/GetTeamResponse.java
- src/main/java/com/moing/backend/domain/team/domain/service/TeamGetService.java
- src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java
> MNG-24 feat: 유저 프로퍼티 추가

- src/main/java/com/moing/backend/domain/member/application/service/UpdateRemindAlarmUseCase.java
- src/main/java/com/moing/backend/domain/mission/application/service/MissionScheduleUseCase.java
v.1.0.7 업데이트 푸시알림
오늘 밤에 스케쥴링 취소해야합니다!
> hotfix : v.1.0.7 업데이트 푸시알림

- src/main/java/com/moing/backend/domain/mission/application/service/MissionScheduleUseCase.java
> hotfix : 업데이트 푸시알림 스케쥴링 삭제

- src/main/java/com/moing/backend/domain/missionComment/application/service/SendMissionCommentAlarmUseCase.java
- missionComment path boardComment로 되어있던것 수정
> MNG-28 fix: missionComment path 수정

- src/main/java/com/moing/backend/domain/board/application/service/SendBoardAlarmUseCase.java
- src/main/java/com/moing/backend/domain/boardComment/application/service/SendBoardCommentAlarmUseCase.java
- src/main/java/com/moing/backend/domain/fire/application/service/FireThrowAlarmUseCase.java
- src/main/java/com/moing/backend/domain/mission/application/service/SendMissionCreateAlarmUseCase.java
- 푸시 알림 클릭 관련 idInfo에 type 추가
|내용|type명|
|------|---|
|공지/게시글 댓글|COMMENT|
|신규 공지|NEW_UPLOAD_BOARD|
|미션 생성|NEW_UPLOAD_MISSION|
|불 던지기|FIRE|
> MNG-28 feat: 푸시 알림 보낼 떼 idInfo에 type 추가
