Modagbul/MOING_Server_Release

src/main/java/com/moing/backend/domain/auth/presentation/AuthController.java
src/main/java/com/moing/backend/domain/member/domain/entity/Member.java
src/main/java/com/moing/backend/domain/mypage/presentation/MyPageController.java
src/main/java/com/moing/backend/global/config/webclient/WebClientConfig.java
src/main/java/com/moing/backend/global/entity/BaseTimeEntity.java

BaseTimeEntity추가
db에 저장되는 엔티티는 (진짜 필요없는 경우 제외하고는) BaseTimeEntity를 상속받아서 사용하기!!
이건 나름 중요한 것 같아서 호다닥 수정해서 pr 날립니다!

feat: BaseTimeEntity추가

---

src/docs/asciidoc/MissionArchive-API.adoc
src/docs/asciidoc/Overview.adoc
src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepository.java
src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/mission/domain/repository/MissionRepository.java
src/main/java/com/moing/backend/domain/mission/domain/service/MissionQueryService.java
src/main/java/com/moing/backend/domain/mission/presentation/MissionController.java
src/main/java/com/moing/backend/domain/missionArchive/application/dto/req/MissionArchiveHeartReq.java
src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/MissionArchiveStatusRes.java
src/main/java/com/moing/backend/domain/missionArchive/application/service/SingleMissionArchiveReadUseCase.java
src/main/java/com/moing/backend/domain/missionArchive/domain/constant/MissionArchiveResponseMessage.java
src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepository.java
src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveQueryService.java
src/main/java/com/moing/backend/domain/missionArchive/presentation/MissionArchiveController.java
src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java

- [미션 인증 좋아요, 미션 인증 인원 조회 구현 및 API 문서 추가](https://github.com/Modagbul/MOING_server_release/commit/fc753dc9a00e01ab47f781683f1ee6263a09bba2)
- [팀별 미션 개수 조회 함수 추가](https://github.com/Modagbul/MOING_server_release/commit/e4c4d61806f5ad042e99f0c869bc226d15332cbe)
- MissionRepository 에서 queryDSL 사용 추가했습니다! 
- MissionArchiveControllerTest 추가 하였습니다.
https://github.com/Modagbul/MOING_server_release/blob/e4c4d61806f5ad042e99f0c869bc226d15332cbe/src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java#L292-L397
- 요청주셨던 팀 별 미션 개수 조회 함수 구현 완료했습니다! 
https://github.com/Modagbul/MOING_server_release/blob/e4c4d61806f5ad042e99f0c869bc226d15332cbe/src/main/java/com/moing/backend/domain/mission/domain/service/MissionQueryService.java#L21-L24 …

feat : 미션 인증 좋아요, 인증 인원 조회, 팀별 미션 개수 조회

---

src/main/java/com/moing/backend/domain/board/application/dto/response/BoardBlocks.java
src/main/java/com/moing/backend/domain/board/domain/repository/BoardCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/boardComment/application/dto/response/CommentBlocks.java
src/main/java/com/moing/backend/domain/boardComment/domain/repository/BoardCommentCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/member/domain/entity/Member.java
src/main/java/com/moing/backend/domain/mypage/application/service/SignOutUserCase.java
src/main/java/com/moing/backend/domain/team/application/service/DisbandTeamUserCase.java
src/main/java/com/moing/backend/domain/team/application/service/WithdrawTeamUserCase.java
src/main/java/com/moing/backend/domain/teamMember/domain/entity/TeamMember.java
src/test/java/com/moing/backend/domain/board/presentation/BoardControllerTest.java
src/test/java/com/moing/backend/domain/boardComment/presentation/BoardCommentControllerTest.java
src/test/java/com/moing/backend/domain/mission/representation/MissionControllerTest.java

소모임 탈퇴 후 닉네임 처리 및 test오류 해결
소모임 탈퇴 후 회원 닉네임 (알 수 없음) 으로 보이게 처리
test build오류 의존성 추가해서 해결
빌드 오류가 생겼기에 바로 머지하겠슴니당!

fix: 소모임 탈퇴 후 회원 닉네임 처리 및 test오류 해결 

---

src/docs/asciidoc/Auth-API.adoc
src/docs/asciidoc/Team-API.adoc
src/main/java/com/moing/backend/domain/team/application/dto/request/UpdateTeamRequest.java
src/main/java/com/moing/backend/domain/team/application/dto/response/UpdateTeamResponse.java
src/main/java/com/moing/backend/domain/team/application/service/UpdateTeamUserCase.java
src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepository.java
src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/team/domain/service/TeamGetService.java
src/main/java/com/moing/backend/domain/team/presentation/TeamController.java
src/main/java/com/moing/backend/domain/team/presentation/constant/TeamResponseMessage.java
src/main/java/com/moing/backend/global/config/security/jwt/TokenUtil.java
src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java

- 소모임 수정 API 구현
- memberId로 List<Long> teamId가져오기
https://github.com/Modagbul/MOING_Server_Release/blob/8e87ca56a5d758b3ba3f844b59746ec487d36615/src/main/java/com/moing/backend/domain/team/presentation/TeamController.java#L88-L98
https://github.com/Modagbul/MOING_Server_Release/blob/8e87ca56a5d758b3ba3f844b59746ec487d36615/src/main/java/com/moing/backend/domain/team/domain/service/TeamGetService.java#L24-L26
요청 메서드는
team> domain > service > TeamGetSErvice에 있슴니당!

Feat: 소모임 수정 및 요청 메서드

---

src/docs/asciidoc/Mypage-API.adoc
src/main/java/com/moing/backend/domain/board/domain/repository/BoardCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/mypage/application/dto/response/GetMyPageResponse.java
src/main/java/com/moing/backend/domain/mypage/application/dto/response/GetMyPageTeamBlock.java
src/main/java/com/moing/backend/domain/mypage/application/mapper/MyPageMapper.java
src/main/java/com/moing/backend/domain/mypage/application/service/GetMyPageUserCase.java
src/main/java/com/moing/backend/domain/mypage/presentation/MyPageController.java
src/main/java/com/moing/backend/domain/mypage/presentation/constant/MypageResponseMessage.java
src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepository.java
src/main/java/com/moing/backend/domain/team/domain/repository/TeamCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/team/domain/service/TeamGetService.java
src/main/java/com/moing/backend/domain/team/exception/AlreadyJoinTeamException.java
src/main/java/com/moing/backend/domain/team/exception/AlreadyWithdrawTeamException.java
src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/teamMember/domain/service/TeamMemberSaveService.java
src/main/java/com/moing/backend/global/response/ErrorCode.java
src/test/java/com/moing/backend/domain/mypage/presentation/MypageControllerTest.java

- 마이페이지 조회
- 소모임 생성 시 탈퇴 회원 , 이미 가입한 회원은 가입할 수 없게 막기
1. 마이페이지 조회
https://github.com/Modagbul/MOING_Server_Release/blob/9c3a141214e79a5977528bb2126698a298d8145a/src/main/java/com/moing/backend/domain/mypage/presentation/MyPageController.java#L56-L64
2. 소모임 생성 에러 처리 추가
https://github.com/Modagbul/MOING_Server_Release/blob/9c3a141214e79a5977528bb2126698a298d8145a/src/main/java/com/moing/backend/domain/teamMember/domain/service/TeamMemberSaveService.java#L18-L37
https://github.com/Modagbul/MOING_Server_Release/blob/d413ef91ca9ba8649884ec05b6bd37f610c256d9/src/test/java/com/moing/backend/domain/mypage/presentation/MypageControllerTest.java#L110-L163

feat: 마이페이지 조회 및 소모임 생성 에러 처리 추가

---

src/docs/asciidoc/Auth-API.adoc
src/docs/asciidoc/Board-API.adoc
src/docs/asciidoc/BoardComment_API.adoc
src/docs/asciidoc/Fire-API.adoc
src/docs/asciidoc/Image-API.adoc
src/docs/asciidoc/Mission-API.adoc
src/docs/asciidoc/MissionArchive-API.adoc
src/docs/asciidoc/MissionBoard-API.adoc
src/docs/asciidoc/MissionGatherBoard-API.adoc
src/docs/asciidoc/Mypage-API.adoc
src/docs/asciidoc/Team-API.adoc
src/docs/asciidoc/api.adoc
src/main/java/com/moing/backend/domain/team/application/dto/response/GetCurrentStatusResponse.java
src/main/java/com/moing/backend/domain/team/application/mapper/TeamMapper.java
src/main/java/com/moing/backend/domain/team/application/service/GetTeamUserCase.java
src/main/java/com/moing/backend/domain/team/presentation/TeamController.java
src/main/java/com/moing/backend/domain/team/presentation/constant/TeamResponseMessage.java
src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java

- 소모임 수정 전 조회 API
- build시 adoc warning 안뜨게 수정
- 소모임 목표보드 API endpoint수정
1. 클라이언트의 요청으로 소모임 수정 전 조회 API를 추가
https://github.com/Modagbul/MOING_Server_Release/blob/33f239451822d35c1a8e20860f3662b1c6c7a471/src/main/java/com/moing/backend/domain/team/presentation/TeamController.java#L107-L115   
2. build시 adoc warning 기존에 뜬 이유
이렇게 없는 부분을 불러오려고 할 때 warning이 뜸 따라서 그 부분을 수정   
3. 소모임 수정 전 조회 API를 "/api/team/{teamId}"로 하면서 기존 소모임 목표보드 API를 "/api/team/board/{teamId}"로 수정했습니다.
위의 변경사항 확인 부탁드립니다~!
https://github.com/Modagbul/MOING_Server_Release/blob/33f239451822d35c1a8e20860f3662b1c6c7a471/src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java#L434-L477

소모임 수정 전 조회 API 만들기

---

src/main/java/com/moing/backend/domain/mission/application/dto/req/MissionReq.java
src/main/java/com/moing/backend/domain/mission/application/service/MissionGatherBoardUseCase.java
src/main/java/com/moing/backend/domain/missionArchive/application/dto/req/MissionArchiveReq.java
src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/MissionArchivePhotoRes.java
src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/MissionArchiveRes.java
src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/PersonalArchiveRes.java
src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveReadUseCase.java
src/main/java/com/moing/backend/domain/missionArchive/domain/constant/MissionArchiveResponseMessage.java
src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepository.java
src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveQueryService.java
src/main/java/com/moing/backend/domain/missionArchive/presentation/MissionArchiveController.java
src/main/java/com/moing/backend/domain/missionArchive/presentation/MissionGatherController.java
src/main/java/com/moing/backend/domain/missionHeart/application/dto/MissionHeartRes.java
src/test/java/com/moing/backend/domain/mission/representation/MissionControllerTest.java
src/test/java/com/moing/backend/domain/missionArchive/representation/MissionGatherControllerTest.java

- mission 관련 dto 객체 lombok 추가
- @Builder,@Getter,@NoArgsConstructor, @AllArgsConstructor 가 없어 오류나는 상황 해결 
- mission API 문서 수정
- 소모임별 초기 화면에 들어갈 팀별 미션 인증물 리턴
- mission 관련 dto 객체 lombok 추가
- 다른건 괜찮은데 왜 mission 관련해서만 에러가 났을까 .. 
- mission API 문서에 enum 값 설명 추가 
- 소모임별 초기 화면에 들어갈 팀별 미션 인증물 리턴

feat : mission 관련 dto 객체 lombok 추가 및 API 문서 수정 /  팀별 미션 인증물 리턴

---

src/docs/asciidoc/MissionGatherBoard-API.adoc

지난번에 pr 날렸던 팀별 미션 모아보기 ( 소모임 메인 사진 리스트 ) 가 api 문서에 반영이 안되어있어 다시 pr 날립니다!

fix : 미션모아보기-팀별 adoc 반영

---

src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/MyMissionArchiveRes.java
src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveCreateUseCase.java
src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveReadUseCase.java
src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveUpdateUseCase.java
src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepository.java
src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveQueryService.java
src/main/java/com/moing/backend/domain/missionArchive/presentation/MissionArchiveController.java
src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java

- 나의 미션 인증 조회 시 당일인증 여부 추가 및 당일 중복 미션 인증 불가

feat : 나의 미션 인증 조회 시 당일인증 여부 추가 및 당일 중복 미션 인증 불가

---

src/main/java/com/moing/backend/domain/team/application/dto/response/TeamInfo.java
src/main/java/com/moing/backend/domain/team/application/mapper/TeamMapper.java
src/main/java/com/moing/backend/domain/team/application/service/GetTeamUserCase.java
src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java

- 목표보드 조회 시 유저 아이디도 같이 넘겨줄 수 있게 수정
TeamInfo에서 
private Long currentUserId; //현재 유저 아이디
추가

목표보드 조회 시 현재 유저 아이디 추가

---

src/docs/asciidoc/Auth-API.adoc
src/main/java/com/moing/backend/domain/auth/presentation/AuthController.java
src/test/java/com/moing/backend/domain/auth/presentation/AuthControllerTest.java

- 닉네임 중복 검사 API endPoint 수정
/api/auth/nickname/NICKNAME → /api/auth/checkNickname?nickname={nickname}

refactor: 닉네임 중복 검사 API endPoint 수정

---

src/main/java/com/moing/backend/domain/member/domain/entity/Member.java
src/main/java/com/moing/backend/domain/member/domain/repository/MemberCustomRepository.java
src/main/java/com/moing/backend/domain/member/domain/repository/MemberCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/member/domain/repository/MemberRepository.java
src/main/java/com/moing/backend/domain/member/domain/service/MemberGetService.java
src/main/java/com/moing/backend/domain/member/domain/service/MemberSaveService.java
src/main/java/com/moing/backend/domain/mypage/application/service/WithdrawUserCase.java
src/main/java/com/moing/backend/domain/teamMember/domain/entity/TeamMember.java

- member 삭제 소프트 삭제로 수정
- 기존에는 member삭제할 때 memberRepository를 이용해 아예 해당 칼럼을 삭제하는 방식이었음 (기획 요청) 
-> member와 연관된 테이블이 많아 소프트 삭제로 수정
- unique 제약조건 삭제
- member을 조회할 때 삭제되지 않은 member을 조회하게 수정
https://github.com/Modagbul/MOING_Server_Release/blob/cfc0748e915a53b6ae1f8a38147a16174b455f38/src/main/java/com/moing/backend/domain/member/domain/repository/MemberCustomRepositoryImpl.java#L29-L53
이렇게 member을 조회할 때 삭제되지 않은 member을 조회하게 수정
member삭제할 때 소프트 삭제로 수정
https://github.com/Modagbul/MOING_Server_Release/blob/cfc0748e915a53b6ae1f8a38147a16174b455f38/src/main/java/com/moing/backend/domain/member/domain/entity/Member.java#L165-L166

member삭제 오류 해결

---

src/main/java/com/moing/backend/domain/team/application/service/CreateTeamUserCase.java
src/main/java/com/moing/backend/global/config/slack/SlackConfig.java
src/main/java/com/moing/backend/global/config/slack/exception/ExceptionEventHandler.java
src/main/java/com/moing/backend/global/config/slack/exception/dto/ExceptionEvent.java
src/main/java/com/moing/backend/global/config/slack/team/TeamCreateHandler.java
src/main/java/com/moing/backend/global/config/slack/team/dto/TeamCreateEvent.java
src/main/java/com/moing/backend/global/config/slack/util/SlackAdapter.java
src/main/java/com/moing/backend/global/config/slack/util/WebhookUtil.java
src/main/java/com/moing/backend/global/exception/GlobalExceptionHandler.java
src/test/java/com/moing/backend/config/CommonControllerTest.java

- Slack 알림 EventPublisher로 수정
- Spring Events를 통해 주요 코드 실행 시 발생하는 이벤트에 대응하는 외부 로직을 처리. 이를 통해 핵심 서비스 로직과 외부 통신 로직의 결합도를 낮추고, 코드의 가독성과 유지보수성을 향상.
- Spring Events 구현을 비동기로 처리하여 시스템의 전반적인 효율성 향상. 이로써 외부 API 호출과 같은 비용이 큰 작업들이 기본 서비스 흐름을 방해하지 않도록 설계.
- 이전에는 팀 생성 서비스와 에러 처리 클래스 내에서 SlackService에 직접적인 의존성이 존재했으나, 이를 Spring의 EventPublisher로 관리하도록 변경. 이는 의존성 주입을 통해 더욱 유연한 코드 구조를 실현하며, 필요에 따라 다른 방식의 이벤트 처리 구현을 쉽게 통합할 수 있게 함.

Slack 알림 EventPublisher로 수정

---

src/main/java/com/moing/backend/domain/team/application/dto/response/ReviewTeamResponse.java
src/main/java/com/moing/backend/domain/team/application/mapper/TeamMapper.java
src/main/java/com/moing/backend/domain/team/application/service/ReviewTeamUseCase.java
src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java

- 삭제 전 조회할 때 유저 닉네임 추가 (클라이언트 요청)

fix: 삭제 전 조회할 때 유저 닉네임 추가

---

src/main/java/com/moing/backend/domain/board/application/service/SendBoardAlarmUseCase.java
src/main/java/com/moing/backend/domain/history/application/dto/response/NewUploadInfo.java
src/main/java/com/moing/backend/domain/history/application/mapper/AlarmHistoryMapper.java
src/main/java/com/moing/backend/domain/mission/application/service/SendMissionCreateAlarmUseCase.java
src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepository.java
src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/teamMember/domain/service/TeamMemberGetService.java

- 알림보낼 때 로그아웃, 알림 여부를 쿼리가 아닌 mapper로 수정

refactor: 알림보낼 때 로그아웃, 알림 여부 쿼리가 아닌 mapper로 수정

---

src/main/java/com/moing/backend/domain/missionState/application/service/MissionStateUseCase.java

- 반복미션 횟수를 모두 채웠을 시 반복미션이 종료되는 버그를 해결했습니다.
- 종료 가능 여부 확인 로직에서 done.equal(total) -> done >= total 로 변경하였습니다.

fix : 반복미션 종료 로직 버그 수정

---

src/main/java/com/moing/backend/domain/fire/domain/repository/FireCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/missionState/domain/repository/MissionStateCustomRepositoryImpl.java

#204 
- 지난주에 모든 인증 완료한 인원 불던지기 리스트에 안뜨는 오류
- 미션 인증 취소가 안되는 오류
- 조건 기준 추가
https://github.com/Modagbul/MOING_Server_Release/blob/734866d238642355c4350ea71c26f41f7728e343/src/main/java/com/moing/backend/domain/fire/domain/repository/FireCustomRepositoryImpl.java#L57-L109
- missionState에서 기한 내 missionState를 필터링 할 수 있는 장치가 없어서 .. 큰일입니다 .. 그치만 미션 다시 인증하기는 당일만 되는데, 다시 인증 하기를 호출할 때가 당일만 호출할 테니 최신순으로 정렬하여 fetchFirst 하려 합니다!
https://github.com/Modagbul/MOING_Server_Release/blob/734866d238642355c4350ea71c26f41f7728e343/src/main/java/com/moing/backend/domain/missionState/domain/repository/MissionStateCustomRepositoryImpl.java#L94-L103

hotfix : 0120 이슈 대응

---

src/main/java/com/moing/backend/domain/alarm/application/MultiAlarmEventUseCase.java
src/main/java/com/moing/backend/domain/alarm/application/SingleAlarmEventUseCase.java
src/main/java/com/moing/backend/domain/fire/application/service/FireThrowAlarmUseCase.java
src/main/java/com/moing/backend/domain/mission/application/service/MissionRemindAlarmUseCase.java
src/main/java/com/moing/backend/global/config/fcm/exception/ExceptionHandler.java
src/main/java/com/moing/backend/global/config/fcm/service/FcmService.java
src/main/java/com/moing/backend/global/config/fcm/service/MessageSender.java
src/main/java/com/moing/backend/global/config/fcm/service/MultiMessageSender.java
src/main/java/com/moing/backend/global/config/fcm/service/SingleMessageSender.java
src/main/java/com/moing/backend/global/config/fcm/util/FcmMessageUtil.java
src/main/java/com/moing/backend/global/config/slack/team/TeamCreateHandler.java

- 알림 센터에서 푸시알림을 클릭했을 떄 이동하게 수정
- 알림 센터에서 푸시알림을 클릭했을 떄 이동할 수 있게 addData추가
- fcm 부분에서 추상화게 의존할 수 있게 함수 구조 리팩토링
-> 우선 기존 함수는 주석 처리했고, 반영 후 리마인드 알림까지 잘 보내지면 후에 삭제할 예정 !
- fcm 부분에서 개방-폐쇄 원칙을 지킬 수 있게 추상화게 의존할 수 있게 했는데 이에 대해 봐주시면 감사하겠습니당

MNG-02 알림센터에서 푸시알림을 클릭했을 때 이동하게 수정

---

src/main/java/com/moing/backend/domain/auth/application/dto/request/SignUpRequest.java
src/main/java/com/moing/backend/domain/mission/application/service/MissionCreateUseCase.java
src/main/java/com/moing/backend/domain/mission/application/service/MissionReadUseCase.java
src/main/java/com/moing/backend/domain/mypage/application/dto/response/GetMyPageResponse.java
src/main/java/com/moing/backend/domain/mypage/application/dto/response/GetMyPageTeamBlock.java
src/main/java/com/moing/backend/domain/mypage/application/mapper/MyPageMapper.java
src/main/java/com/moing/backend/domain/mypage/application/service/GetMyPageUseCase.java
src/main/java/com/moing/backend/domain/team/application/dto/request/CreateTeamRequest.java
src/main/java/com/moing/backend/domain/team/application/dto/response/GetNewTeamResponse.java
src/main/java/com/moing/backend/domain/team/application/dto/response/GetTeamDetailResponse.java
src/main/java/com/moing/backend/domain/team/application/dto/response/TeamBlock.java
src/main/java/com/moing/backend/domain/team/application/dto/response/TeamInfo.java
src/main/java/com/moing/backend/domain/team/application/mapper/TeamMapper.java
src/main/java/com/moing/backend/domain/team/domain/constant/Category.java
src/main/java/com/moing/backend/domain/team/domain/entity/Team.java
src/test/java/com/moing/backend/domain/mypage/presentation/MypageControllerTest.java
src/test/java/com/moing/backend/domain/team/presentation/TeamControllerTest.java

- 모임 만들 때 카테고리 직접 입력할 수 있게 카테고리 enum 제거
- Category enum 클래스는 정적이므로 string으로 수정

MNG-05 모임 만들 때 카테고리 직접 입력할 수 있게 category enum 제거

---

src/main/java/com/moing/backend/domain/boardComment/application/service/CreateBoardCommentUseCase.java
src/main/java/com/moing/backend/domain/boardComment/application/service/SendCommentAlarmUseCase.java
src/main/java/com/moing/backend/global/config/fcm/constant/NewCommentUploadMessage.java

- 유저가 작성한 공지/게시글에 댓글이 달리면, 해당 유저에게 푸시 알림을 발송하도록 추가
- 댓글이 생성되면 그 댓글의 게시글을 쓴 유저에게 알림을 보냄

MNG-06 유저가 작성한 공지/게시글에 댓글이 달리면, 해당 유저에게 푸시 알림을 발송하도록 추가

---

.gitignore
src/main/java/com/moing/backend/domain/mission/application/service/MissionCreateUseCase.java

➡️ 반복 미션을 즉시 시작할 수 있도록 변경함
1. 미션 생성시 WAIT 상태로 미션 만들어짐. 
2. 한번 미션은 new 미션! 하고 태그가 뜨도록 함. 팀원 중 누군가가 인증을 하게 된다면 ongoing으로 변경. **그대로 유지**
3. 반복 미션은 유예 상태였음. 한번/반복 미션 공통 MissionMapper 에는 WAIT로 Mission 객체를 만들지만, 반복 미션에 따른 다른 제약 사항, 예외 처리 부분이 있기에 **객체 생성 후 반복미션임을 확인하고 예외를 모두 통과한다면 ONGOING으로 updateStatus 하도록 함**

MNG-08 : 반복 미션 즉시 시작할 수 있도록 유예 기간 해제

---

src/main/java/com/moing/backend/domain/mission/application/service/MissionCreateUseCase.java
src/main/java/com/moing/backend/domain/mission/application/service/MissionUpdateUseCase.java

➡️ 한번 미션은 모든 모임원들이 생성할 수 있도록 변경 
➡️ 소모임장에게 [모든 한번 미션에 대한 ‘미션 종료하기’ 권한] 부여
- 미션 생성에서 소모임장인지 확인하는 로직 삭제 → 모든 모임원이 미션 생성 할 수 있음
- 기존 미션 종료하기 API는 반복 미션 종료용 API로 소모임장 확인 로직이 포함되어 있었음. 그대로 사용하면 될듯

MNG-12 : 미션 생성 권한 변경, 소모임장에게 미션 종료하기 권한 부여

---

src/main/java/com/moing/backend/domain/history/application/service/GetAlarmHistoryUseCase.java
src/main/java/com/moing/backend/domain/history/domain/repository/AlarmHistoryCustomRepositoryImpl.java

- 알림 히스토리 모두 읽음 처리
- 알림 히스토리 전체 조회할 때 해당 사용자의 히스토리를 모두 읽음 처리하게 수정

MNG-14 fix: 알림 히스토리 전체 조회할 때 모두 읽음 처리

---

src/main/java/com/moing/backend/domain/block/domain/entity/Block.java
src/main/java/com/moing/backend/domain/block/domain/repository/BlockRepositoryUtils.java
src/main/java/com/moing/backend/domain/board/application/dto/response/BoardBlocks.java
src/main/java/com/moing/backend/domain/board/domain/repository/BoardCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/boardComment/application/dto/response/CommentBlocks.java
src/main/java/com/moing/backend/domain/boardComment/domain/repository/BoardCommentCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepository.java
src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/teamMember/domain/service/TeamMemberGetService.java
src/test/java/com/moing/backend/domain/board/domain/BoardRepositoryTest.java

- 기존에는 프론트엔드에서 처리했지만 로딩 시간이 지연되어서 서버에서 아예 처리하고 보내주려고 합니닷 !!
- 차단한 멤버가 작성한 게시글 / 댓글 보이지 않기
- 목표보드 안 읽은 게시글에서 차단한 멤버가 작성한 것 제외
- 차단한 멤버가 새로 만든 공지 / 미션은 포함하지 않음 
++) 게시글 댓글 관련 알림은 어차피 수정될 것 같아 우선 건드리지 않았습니다 !
- BlockRepositoryUtils.blockCondition()함수를 static으로 만들고 이를 호출하는 형식으로 했습니다 !!

MNG-15 feat : 차단한 멤버 관리 로직 추가 (게시글/댓글 목록)

---

src/main/java/com/moing/backend/domain/boardComment/application/service/SendCommentAlarmUseCase.java
src/main/java/com/moing/backend/domain/boardComment/domain/repository/BoardCommentCustomRepository.java
src/main/java/com/moing/backend/domain/boardComment/domain/repository/BoardCommentCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/boardComment/domain/service/BoardCommentGetService.java

- 댓글 작성자에게도 알림 가게 기능 추가
- 기존에는 해당 게시글 작성자에게만 알림이 가게 했다면 이제는 거기에 더해 댓글 작성자에게도 알림이 가게 수정
- 댓글 알림에도 차단 멤버 관리 로직이 추가됨
- 댓글 알림 로직... 저게 최선인것인가 ??

MNG-17 feat: 댓글 작성자에게도 알림 가게 기능 추가

---

src/main/java/com/moing/backend/domain/fire/domain/repository/FireCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/team/application/service/GetTeamUseCase.java
src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepository.java
src/main/java/com/moing/backend/domain/teamMember/domain/repository/TeamMemberCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/teamMember/domain/service/TeamMemberGetService.java

-  기존에는 클라이언트가 처리했던 부분(차단 멤버 관리)을 서버에서 처리하게 수정
- 모임원 소개에 차단 멤버 보이지 않게
- 미션 인증물 조회에서 차단 멤버가 한 것은 보이지 않게
- 불 던질 사람 조회할 때 차단 멤버 보이지 않게
- 미션쪽과 불 던지기 부분 확인 부탁 드립니다 :)

MNG-15 fix: 차단 멤버 관리 : 모인원 소개, 미션 인증, 불 던지기

---

src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveDeleteUseCase.java

미션 건너뛰기 취소 안되는 버그 해결
예외처리를 잘하자!
애증의 조건문 남겨드립니다 .. 
if (deleteArchive.getStatus().equals(MissionArchiveStatus.COMPLETE) && mission.getWay().equals(MissionWay.PHOTO)) {

MNG-16 fix : 미션 건너뛰기 취소 안되는 버그 해결

---

src/main/java/com/moing/backend/domain/teamScore/application/service/TeamScoreGetUseCase.java

레벨 70 이상 일 때 score가 100 넘기에 레벨 70 이상 조정

hotfix : 레벨 70 이상 목표보드 에러

---

src/main/java/com/moing/backend/domain/missionArchive/application/dto/req/MissionArchiveReq.java
src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/MissionArchiveRes.java
src/main/java/com/moing/backend/domain/missionArchive/application/dto/res/PersonalArchiveRes.java
src/main/java/com/moing/backend/domain/missionArchive/application/mapper/MissionArchiveMapper.java
src/main/java/com/moing/backend/domain/missionArchive/domain/entity/MissionArchive.java
src/main/java/com/moing/backend/domain/teamScore/application/service/TeamScoreGetUseCase.java
src/test/java/com/moing/backend/domain/missionArchive/representation/MissionArchiveControllerTest.java

- 미션 인증 시 문구 추가 
- MissionArchive 에 contents 칼럼 추가
- nullable 설정
- 관련 dto,mapper에 관련 칼럼 추가
- 엔티티 변경사항 있으니 업데이트 반영 시 고려해야할 것 같아요.
- 미션 인증 댓글 기능과 관련해 엔티티 부분에서 충돌 사항 생길 수 있으니 주의 해야할 것 같아요!

MNG-21 : 미션 인증 시 문구 추가

---

src/main/java/com/moing/backend/domain/mission/application/dto/res/GatherSingleMissionRes.java
src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java
src/test/java/com/moing/backend/domain/missionArchive/representation/MissionGatherControllerTest.java

반복미션 모아보기 인증 인원수 리턴 타입 변경
클라 요청대로 인원수 리턴타입 변경하였습니다!

MNG-22 : 반복미션 모아보기 인증 인원수 리턴 타입 변경

---

src/main/java/com/moing/backend/domain/missionArchive/application/service/MissionArchiveDeleteUseCase.java
src/main/java/com/moing/backend/domain/missionArchive/domain/service/MissionArchiveDeleteService.java
src/main/java/com/moing/backend/domain/missionComment/domain/repository/MissionCommentRepository.java
src/main/java/com/moing/backend/domain/missionComment/domain/service/MissionCommentDeleteService.java

미션 재인증(삭제) 시 연관관계에 있는 missionComment 삭제 로직 추가
- MissionArchive DB 삭제하려고 하던중 연관관계에 있는 MissionComments 가 있어 삭제할 수 없다는 에러를 발견하였습니다.
- missionArchive 가 같은 missionComment 들을 모두 삭제하는 datajpa 메소드를 추가하고 이를 사용한 로직을 추가하였습니다.
https://github.com/Modagbul/MOING_Server_Release/blob/2f41dc7a6e82380c906f963e3d45362b496ac9dc/src/main/java/com/moing/backend/domain/missionComment/domain/service/MissionCommentDeleteService.java#L19-L21
https://github.com/Modagbul/MOING_Server_Release/blob/2f41dc7a6e82380c906f963e3d45362b496ac9dc/src/main/java/com/moing/backend/domain/missionComment/domain/repository/MissionCommentRepository.java#L13

[MNG-21] hotfix : 미션 재인증(삭제) 시 500에러 해결

---

src/main/java/com/moing/backend/domain/report/application/service/ReportCreateUseCase.java
src/main/java/com/moing/backend/domain/report/domain/entity/constant/ReportType.java
src/test/java/com/moing/backend/domain/report/presentation/ReportControllerTest.java

미션 댓글 신고하기 추가
미션 댓글 신고하기 추가
저기가 너무 하드코딩이 되어서,,, 저 부분은 OCP 지키게 리팩토링이 필요해 보입니다

MNG-20 feat: 미션 댓글 신고하기

---

src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java

반복미션 오늘 인증 여부 확인 하는 로직 수정
- 반복미션 오늘 인증 여부를 확인할 때 lastModifiedDate 를 이용했었는데, missionArchive 에 commentNum 이 추가되고 댓글 추가에 따라 이를 수정하면서 lastedModifiedDate 가 계속 업데이트 되었습니다. 그래서 오늘 인증 가능한 상황이어도 인증 할 수 없는 값으로 리턴되는 문제가 발생하였습니다.
- 그래서 쿼리문의 lastModifiedDate 를 createdDate 로 변경하였습니다!
https://github.com/Modagbul/MOING_Server_Release/blob/ed3eee48fbce1ed7a0940d6f97363709b9a4b82d/src/main/java/com/moing/backend/domain/missionArchive/domain/repository/MissionArchiveCustomRepositoryImpl.java#L362-L384

hotfix fix : 반복미션 오늘 인증 여부 확인 하는 로직 수정

---

src/main/java/com/moing/backend/domain/mission/domain/repository/MissionCustomRepositoryImpl.java

1차 QA 중 한번 미션 블록 정렬 규척이 적용되어 있지 않아요. 적용
진행중 미션-한번미션 조회 쿼리 중 정렬 조건을 추가하였습니다.

MNG-22 fix : 한번미션 정렬 기준 변경

---

src/main/java/com/moing/backend/domain/board/domain/entity/Board.java
src/main/java/com/moing/backend/domain/boardComment/domain/entity/BoardComment.java
src/main/java/com/moing/backend/domain/missionArchive/domain/entity/MissionArchive.java
src/main/java/com/moing/backend/domain/missionComment/domain/entity/MissionComment.java
src/main/java/com/moing/backend/domain/report/application/service/BoardCommentReportStrategy.java
src/main/java/com/moing/backend/domain/report/application/service/BoardReportStrategy.java
src/main/java/com/moing/backend/domain/report/application/service/MissionArchiveReportStrategy.java
src/main/java/com/moing/backend/domain/report/application/service/MissionCommentReportStrategy.java
src/main/java/com/moing/backend/domain/report/application/service/ReportCreateUseCase.java
src/main/java/com/moing/backend/domain/report/application/service/ReportStrategy.java
src/main/java/com/moing/backend/domain/report/presentation/ReportController.java
src/main/java/com/moing/backend/domain/report/presentation/constant/ReportResponseMessage.java
src/main/java/com/moing/backend/domain/report/presentation/constant/StrategyCategory.java
src/main/java/com/moing/backend/domain/teamMember/domain/entity/TeamMember.java
src/test/java/com/moing/backend/domain/report/presentation/ReportControllerTest.java
src/test/java/com/moing/backend/domain/team/application/service/CreateTeamUseCaseTest.java

- 신고하기 기능 전략패턴 적용해 유지보수성 높임
- 기존에는 여러 종류 (댓글, 게시글, 미션 게시글, 미션 댓글)이 모두 하나의 클래스에서 if-else로 되어 있어 OCP를 지키지 못함
- 따라서 전략패턴을 적용해 런타임시 해당 도메인의 신고하기 기능을 선택하게 해 OCP를 지켜 유지보수성을 높임
- MissionArchiveReportStrategy 부분이 여전히 if-else문이 남아 있는데 이 부분 수정 부탁드립니다...
https://github.com/Modagbul/MOING_Server_Release/blob/174b92a4e6e3a7990a8b0940b0dc676692e709f0/src/main/java/com/moing/backend/domain/report/application/service/MissionArchiveReportStrategy.java#L19-L50

refactor : 신고하기 기능 전략패턴 적용

---

src/main/java/com/moing/backend/domain/member/application/service/UpdateRemindAlarmUseCase.java
src/main/java/com/moing/backend/domain/mission/application/service/MissionScheduleUseCase.java

FCM 발송 제한으로 500명씩 나눠서 보내기
FCM 은 한번에 500건 이상 발송 불가. 이후 배치 작업 해야할듯합니다!

Hotfix : FCM 발송 제한으로 500명씩 나눠서 보내기

---

src/main/java/com/moing/backend/domain/member/domain/entity/Member.java

- 회원가입 시 미션 댓글 알림 여부 수정
- 회원가입할 때 미션 댓글 알림 여부도 true로 수정 (디폴트 값)

fix: 회원가입시 미션댓글 알림 여부 true로 수정

---

src/main/java/com/moing/backend/domain/boardComment/application/service/SendBoardCommentAlarmUseCase.java
src/main/java/com/moing/backend/domain/fire/application/service/FireThrowAlarmUseCase.java
src/main/java/com/moing/backend/domain/missionArchive/application/service/SendMissionArchiveCreateAlarmUseCase.java
src/main/java/com/moing/backend/domain/missionComment/application/service/SendMissionCommentAlarmUseCase.java

- 푸시 알림 클릭 관련 idInfo에 type 추가
|내용|type명|
|------|---|
|공지/게시글 댓글|COMMENT_BOARD|
|미션 댓글|COMMENT_MISSION|
|신규 공지|NEW_UPLOAD_BOARD|
|미션 생성|NEW_UPLOAD_MISSION|
|불 던지기(메시지 있음)|FIRE_MESSAGE_EXIST|
|불 던지기(메시지 없음)|FIRE_MESSAGE_NULL|
|미션 인증하기|COMPLETE_MISSION|

MNG-28 feat: 푸시알림 보낼 때 idInfo에 tyep 추가 - 2

---

.github/workflows/CD-prod.yml
.github/workflows/CI-dev.yml
.github/workflows/CI-prod.yml
build.gradle
src/main/java/com/moing/backend/domain/history/presentation/AlarmHistoryController.java
src/main/java/com/moing/backend/domain/member/application/service/UpdateRemindAlarmUseCase.java
src/main/java/com/moing/backend/domain/member/domain/repository/MemberCustomRepository.java
src/main/java/com/moing/backend/domain/member/domain/repository/MemberCustomRepositoryImpl.java
src/main/java/com/moing/backend/domain/member/domain/repository/MemberRepository.java
src/main/java/com/moing/backend/domain/member/domain/service/MemberGetService.java
src/main/java/com/moing/backend/domain/member/dto/request/PostUpdatePushAlarm.java
src/main/java/com/moing/backend/domain/member/presentation/RemindAlarmController.java
src/main/java/com/moing/backend/global/config/fcm/service/MultiMessageSender.java

hotfix: 업데이트 푸시알림 + FCM SDK 업데이트

---

src/main/java/com/moing/backend/global/config/fcm/exception/ExceptionHandler.java

fix: fcm 메시지 전송 실패 로그 출력
